version: '3'

services:
  # Service MySQL
  db:
    image: mysql:8.0
    container_name: TrelluContainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trellu_db
      MYSQL_USER: roott
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: